[package]
name = "ronarudoog/satchel"
description = "A modern open-source alternative to Roblox's default backpack. Forked by Ronarudo for extra methods"
version = "0.1.0"
authors = ["Ronarudo", "Ryan Luu <ryan.luu@ryanluu.dev>"]
realm = "shared"
repository = "https://github.com/ronarudoog/satchel"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.4.0"
